development:
  adapter: postgresql
  encoding: unicode
  database: photogram_dev
  host: localhost
  pool: 5
  username: pkuttiya
  password: p053851238

test:
  adapter: postgresql
  encoding: unicode
  database: photogram_test
  host: localhost
  pool: 5
  username: pkuttiya
  password: p053851238